version: '3.7'

services:
  userapp:
    container_name: userapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000

  prometheus:
    image: prom/prometheus
    restart: 'no'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090